export const KEYWORDS = [
  '3D Printing',
  'Abstract Art',
  'Acrobatics',
  'Affiliate Marketing',
  'Alternative Medicine',
  'Antique Collecting',
  'Archery',
  'Aromatherapy',
  'Artificial Intelligence',
  'Astrology',
  'Astronomy',
  'Astrophotography',
  'Augmented Reality',
  'Auto Detailing',
  'Backpacking',
  'Badminton',
  'Baking',
  'Ballet',
  'Biochemistry',
  'Blogging',
  'Board Games',
  'Bodybuilding',
  'Bonsai',
  'Bread Making',
  'Bubble Tea Making',
  'Business',
  'Calligraphy',
  'Camping',
  'Card Tricks',
  'Career Development',
  'Chemistry',
  'Chess',
  'Classical Music',
  'Community Building',
  'Composting',
  'Cooking',
  'Cooking Techniques',
  'Copywriting',
  'Cosplay',
  'Creative Writing',
  'Crossfit',
  'Cryptocurrency',
  'Cryptography',
  'Cyberpunk',
  'Cybersecurity',
  'Cycling',
  'Dance',
  'Data Analysis',
  'Digital Art',
  'Digital Marketing',
  'DIY',
  'Drawing',
  'Drone Photography',
  'Dungeons & Dragons',
  'E-commerce',
  'Ecology',
  'Education',
  'Electric Vehicles',
  'Entrepreneurship',
  'Environmental Activism',
  'Escape Rooms',
  'Event Management',
  'Fantasy',
  'Fashion',
  'Feng Shui',
  'Film Making',
  'Finance',
  'Fishing',
  'Fitness',
  'Fitness Nutrition',
  'Fitness Tracking',
  'Folk Music',
  'Freelancing',
  'Futurism',
  'Game Development',
  'Gaming',
  'Gardening',
  'Gardening Techniques',
  'Genealogy',
  'Geocaching',
  'Glass Blowing',
  'Goal Setting',
  'Graphic Design',
  'Guitar Playing',
  'Hand Lettering',
  'Health',
  'Herbal Medicine',
  'Hiking',
  'Historical Reenactment',
  'Home Brewing',
  'Home Improvement',
  'Horror',
  'Human Psychology',
  'Ice Skating',
  'Illustration',
  'Indoor Gardening',
  'Interior Decoration',
  'Interior Design',
  'Investing',
  'Jazz Music',
  'Jewelry Making',
  'Journaling',
  'Journalism',
  'Juggling',
  'Karate',
  'Kayaking',
  'Knitting',
  'Language Learning',
  'Languages',
  'Lego Building',
  'Lifestyle',
  'Magic Performance',
  'Magic Tricks',
  'Makeup Artistry',
  'Machine Learning',
  'Manuscript Writing',
  'Marketing',
  'Martial Arts',
  'Meditation',
  'Mental Health',
  'Metal Music',
  'Mind Mapping',
  'Mindfulness',
  'Minimalism',
  'Mixed Martial Arts',
  'Model Railroading',
  'Motivation',
  'Mountain Biking',
  'Mountain Climbing',
  'Music',
  'Music Production',
  'Mythic Beasts',
  'Mythology',
  'Networking',
  'Nutrition',
  'Origami',
  'Outdoor Adventures',
  'Painting',
  'Paleontology',
  'Parenting',
  'Park Design',
  'Parkour',
  'Perfume Making',
  'Personal Finance',
  'Personal Growth',
  'Pets',
  'Photography',
  'Physics',
  'Pilates',
  'Plant-Based Cooking',
  'Plastic Recycling',
  'Podcast Hosting',
  'Podcast Production',
  'Podcasting',
  'Poetry',
  'Poledance Fitness',
  'Pottery',
  'Product Design',
  'Productivity',
  'Programming',
  'Public Relations',
  'Punk Rock',
  'Puzzle Solving',
  'Quilting',
  'RC Vehicles',
  'Real Estate',
  'Recycling',
  'Retro Aesthetics',
  'Robot Building',
  'Robotics',
  'Rock Climbing',
  'Rock Music',
  'Rope Climbing',
  'Running',
  'Sailing',
  'Science',
  'Science Fiction Writing',
  'Scrapbooking',
  'Scuba Diving',
  'Self-Care',
  'Self-Publishing',
  'SEO (Search Engine Optimization)',
  'Sewing',
  'Shibari',
  'Singing',
  'Sketching',
  'Skydiving',
  'Slacklining',
  'Soap Making',
  'Social Media',
  'Space Exploration',
  'Spelunking',
  'Spiritual Growth',
  'Sports',
  'Steam Punk',
  'Stone Carving',
  'Storyboarding',
  'Storytelling',
  'Street Art',
  'Surfing',
  'Survival',
  'Sustainability',
  'Swimming',
  'Tattoo Art',
  'Tattoo Design',
  'Technology',
  'Theatre',
  'Tourism',
  'Trail Running',
  'Trampoline Fitness',
  'Travel',
  'Treasure Hunting',
  'Triathlon',
  'Urban Exploration',
  'Urban Gardening',
  'UX/UI Design',
  'Vehicle Restoration',
  'Video Editing',
  'Violin Playing',
  'Virtual Assistants',
  'Virtual Reality',
  'Vlogging',
  'Volunteering',
  'Watercolor Painting',
  'Weightlifting',
  'Wheel Throwing',
  'Wildlife Conservation',
  'Wildlife Photography',
  'Wilderness Medicine',
  'Wilderness Survival',
  'Wine Tasting',
  'Wood Carving',
  'Woodworking',
  'World Building',
  'Writing',
  'Yoga',
  'Zen Gardens',
  'Zero Waste Living',
  'Zumba',
];
