export const KEYWORDS = [
  'Cooking',
  'Fitness',
  'Travel',
  'Technology',
  'Business',
  'Health',
  'Education',
  'Science',
  'Art',
  'Music',
  'Gardening',
  'Sports',
  'Parenting',
  'Lifestyle',
  'Meditation',
  'Finance',
  'Productivity',
  'Photography',
  'DIY',
  'History',
  'Languages',
  'Programming',
  'Marketing',
  'Writing',
  'Fashion',
  'Gaming',
  'Nutrition',
  'Yoga',
  'Pets',
  'Sustainability',
  'Self-Care',
  'Motivation',
  'Home Improvement',
  'Digital Art',
  'Personal Growth',
  'Social Media',
  'Interior Design',
  'Steam Punk',
  'Cyberpunk',
  'Fantasy',
  'Horror',
  'Adventure',
  'Survival',
  'Mythology',
  'Space Exploration',
  'Robotics',
  'Artificial Intelligence',
  'Virtual Reality',
  'Ecology',
  'Retro Aesthetics',
  'Urban Exploration',
  'Graphic Design',
  'Blogging',
  'Copywriting',
  'Affiliate Marketing',
  'Cryptocurrency',
  'Blockchain',
  'E-commerce',
  'Product Design',
  'UX/UI Design',
  'Virtual Assistants',
  'Freelancing',
  'Event Management',
  'Hospitality',
  'Tourism',
  'Wilderness Survival',
  'Martial Arts',
  'Woodworking',
  'Creative Writing',
  'Screenwriting',
  'Music Production',
  'Podcasting',
  'Wildlife Photography',
  'Storytelling',
  'Aromatherapy',
  'Interior Decoration',
  'Networking',
  'Public Relations',
  'Journalism',
  'Digital Marketing',
  'SEO (Search Engine Optimization)',
  'Machine Learning',
  'Game Development',
  'Board Games',
  'Card Tricks',
  'Biochemistry',
  'Botany',
  'Chemistry',
  'Physics',
  'Astronomy',
  'Wildlife Conservation',
  'Poetry',
  'Dance',
  'Theatre',
  'Mythic Beasts',
  'Spiritual Growth',
  'Antique Collecting',
  'Tarot Reading',
  'Astronomy',
  'Goal Setting',
];
